resilience4j:
  circuitbreaker:
    configs:
      my-resilience4j-config:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      products:
        base-config: my-resilience4j-config
  timelimiter:
    configs:
      my-timeout-config:
        timeout-duration: 4s
    instances:
      products:
        base-config: my-timeout-config


spring:
  cloud:
    gateway:
      routes:
        - id: products-mcsv
          uri: lb://products-mcsv
          predicates:
            - Path=/api/products/**
            #- Header=token, \d+
            #- Method=GET, POST
            #- Query=color, verde
            #- Cookie=color, azul
            #- Header=Content-Type, application/json
          filters:
            - name: CircuitBreaker
              args:
                  name: products
                  statusCodes: 500
                  fallbackUri: forward:/api/items/5
            - StripPrefix=2
        - id: items-mcsv
          uri: lb://items-mcsv
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2